# Generated by Django 4.2.10 on 2024-04-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Info',
                'verbose_name_plural': 'Info',
                'db_table': 'info',
            },
        ),
    ]
