# Generated by Django 4.2.10 on 2024-04-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
